### ISSUE TITLE
EXtension had problems with QA test 

### ISSUE THREAD

**Issue by dimdimich** [swissup/testimonials#4]
The reason for the previous failure is that the extension fails to send an email and the testimonial is not saved properly. This causes the testimonial to not appear in the admin as mentioned in the previous reviews.
We suggest either to consider making the email success a condition for the success message on the front-end, or save the testimonial regardless of the email status.

Today, testing was carried out by not enabling the "Email notification for admin on new testimonial" field. The functionality works as said in this case.

**Comment by roma84** [comment]
Fixed in d2994ca83a9e22cb47f552db3ff79be151eb141f
